print ("Holla amigo")
print ("Great to see you here...again :...:")
print ("Today, we shall be dividing three numbers")
r = int(input("I want to divide:"))
a = int (input("by:"))
y = int (input("and then by:"))
s = (r/a/y)
print ("Behold! Your quotient is:", s)
print ("Keep using our program!!")
