print ("H e l l o")
print ("We are going to do some floor division right away. You don't know what that is? Oof! Just keep using the program :)")
t = int(input("What do you want to divide?"))
i = int(input("By what do you want to divide?"))
e = int (input("Just give one more value. Thank you"))
r = (t//i//e)
print ("The result of your floor division is", r)
print ("Just in case you haven't noticed, floor division gives only the quotient when you divide.")
print ("Yes, I know, this program is smart")
print ("No more programs. Byeee!!!!! :)")
