print ("Hello User")
print ("I knew you would come back !)")
print ("This time around, we will be multiplying three numbers")
s = int(input("The first number is:"))
a = int(input("The second number is:"))
d = int(input("The third number is:"))
e = (s*a*d)
print ("The product is:", e)
print ("We can never fail you :) Come back again. Byee!!")