print ("Hello User")
print ("Glad you are back again :)")
print ("This program carries out subtraction on three numbers.")
a = int(input("Give the first number:"))
b = int(input("Give the second number:"))
c = int (input("Give the third number:"))
d = (a-b-c)
print ("The difference is", d)
print ("I know we are always right. Catch you next time. Byee!! ^^")